#include "consts.h"

const char* KEYWORDS[] = {R0, R1, R2, R3, R4, R5, R6, R7, MOV, CMP, ADD, SUB, NOT, CLR, LEA, INC, DEC, JMP, BNE,
GET, PRN, JSR, RTS, HLT, MACRO_START, MACRO_END, DATA, STRING, STRUCT, ENTRY, EXTERN};