hara
macro m3sdgfdsfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
dfdfds
sdfsdfs
endmacro
m3sdgfdsfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
macro mov
dfdfds
sdfsdfs
endmacro
m1
jo3der: mov hara,r2